export const environment = {
  production: true,
  URL_INSTAGRAM: '$_URL_INSTAGRAM_GITHUB_VAR',
  URL_TWITTER: '$_URL_TWITTER_GITHUB_VAR',
  URL_FACEBOOK: '$_URL_FACEBOOK_GITHUB_VAR',
  MAX_AMOUNT_IMAGES_CAN_DOWNLOAD: '$_MAX_AMOUNT_IMAGES_CAN_DOWNLOAD',
  TERMS_OF_USE: `$_TERMS_OF_USE`,
  URL_BACK_END: `$_URL_BACK_END`,
};
